config/routes.rb
SampleApp::Application.routes.draw do
  
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  root 'static_pages#home'
  
  get '/signup',  to: 'users#new'
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	
  validates :user_id, presence: true
  belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save {email.downcase!}
  before_create :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  validates :password, length: {minimum: 6}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  
  has_many :microposts
  
  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
  
  def create_remember_token
  	self.remember_token = User.encrypt(User.new_remember_token)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	
  def new
  end
  
  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	  sign_in(user)
  	  redirect_back_or user
  	else
  	  flash.now[:error] = "Invalid email/password combination!"
  	  render 'new'
  	end
  end
  
  def destroy
  	if signed_in?
  	  sign_out
  	  redirect_to root_url
  	else
  	  redirect_to signin_path
  	end
  end	
  
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, 		only: [:index, :edit, :update]
  before_action :correct_user,   		only: [:edit, :update]
  before_action :admin_user,     		only: :destroy
  before_action :for_signed_in_users,   only: [:new, :create]
  
  def index
  	@users = User.paginate(page: params[:page])
  end
  	
  def show
  	@user = User.find(params[:id])
  end
  
  def new
  	@user = User.new
  end
  
  def create
  	@user = User.new(user_params)
  	if @user.save
  	  sign_in @user
  	  flash[:success] = "Wellcome to the Sample App!"
  	  redirect_to @user
  	else
  	  render 'new'
  	end
  end
  
  def edit
  	
  end
  
  def update
  	if @user.update_attributes(user_params)
  	  flash[:success] = "Profile updated!"
  	  redirect_to @user
  	else
  	  render 'edit'
  	end
  end
  
  def destroy
  	@user = User.find(params[:id])
  	if @user.admin?
  	  redirect_to root_url
  	else
  	  @user.delete
  	  flash[:success] = "User deleted!"
  	  redirect_to users_url
  	end
  end
  
  
  private
  
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def signed_in_user	#Если не вошли и пытамся что-то делать
  	unless signed_in?
  	  store_location
  	  redirect_to signin_url, notice: "Please sign in."
  	end
  end
  
  def correct_user     #Если вошли, но хотим поменять данные другого юзера
  	@user = User.find(params[:id])
  	redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
  	redirect_to(root_url) unless current_user.admin?
  end
  
  def for_signed_in_users
  	redirect_to(root_url) if signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
  def full_title(page_title)
  	base_title = "Ruby on Rails Tutorial Sample App"
  	if page_title.empty?
  	  base_title
  	else
  	  "#{base_title} | #{page_title}" 
  	end
  end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  def sign_in(user)
  	remember_token = User.new_remember_token
  	cookies.permanent[:remember_token] = remember_token
  	user.update_attribute(:remember_token, User.encrypt(remember_token))
  	self.current_user = user
  end
  
  def sign_out
  	current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
  	cookies.delete(:remember_token)
  	self.current_user = nil
  end
  
  def current_user=(user)  #первый раз вошли
  	@current_user = user
  end
  
  def current_user         #после послед перехoдов по страницам приложения
  	remember_token = User.encrypt(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def signed_in?
  	!current_user.nil?
  end
  
  def current_user?(user)
  	user == current_user
  end
  
  def redirect_back_or(default)
  	redirect_to(session[:return_to] || default)
  	session.delete(:return_to)
  end
  
  def store_location
  	session[:return_to] = request.url if request.get?
  end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
  def gravatar_for(user, options = {size: 50})
  	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  	size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
	
end

app/views/application/_footer.html.haml
%footer.footer
  %small
    %a{href: "http://railstutorial.org/"} Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{href: "http://news.railstutorial.org/"} News

app/views/application/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if signed_in?
            %li
              = link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", session_path(current_user), method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/application/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "shim"%>
</head>
<body>
  <%= render "header" %>
    <div class="container">
      <% flash.each do |key, value|%>
        <div class="alert alert-<%= key %>"><%= value%></div>
      <%end%>
      <%= yield %>
      <%= render "footer"%>
      <%= debug(params) if Rails.env.development?%>
    </div>
    
</body>
</html>

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert_error
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li * #{msg}

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%p
  The
  %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with
  = succeed "." do
    %a{href: "http://rubyonrails.org/"} Ruby on Rails

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  = succeed "." do
    %a{href: "http://railstutorial.org/contact"} contact page

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  = succeed "." do
    %a{href: "http://railstutorial.org/help"} Rails Tutorial help page
  = succeed "." do
    %a{href: "http://railstutorial.org/book"} Rails Tutorial book

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 Welcome to the Sample App
  %h2
    This is the home page for the
    %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
= link_to image_tag("rails.jpg", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/_form.html.haml
= render 'shared/error_messages'
= f.label :name
= f.text_field :name
      
= f.label :email
= f.text_field :email
      
= f.label :password
= f.password_field :password
      
= f.label :password_confirmation, "Confirm password"
= f.password_field :password_confirmation

app/views/users/_user.html.haml
%li
  = gravatar_for user, size:52
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | #{link_to "delete", user, method: :delete, data: {confirm: "Are you shure?"}}

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'form', f: f      
      = f.submit "Save changes", class: "btn btn-large btn-primary"
      
    = gravatar_for @user
    %a{href: "http://gravatar.com/emails", target: "_blank"} change
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users

= will_paginate

%ul.users
  = render @users
    
     
= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign Up')
%h1 Sign Up

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'form', f: f
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.span4
    %section
      %h1
        = gravatar_for @user
        = @user.name

= @user.name
, #{@user.email}